### PR TITLE
HW4 Task03

### PR DESCRIPTION
**Pull request by LinaKrevetochka**

### CODE REVIEW

**Review by Cjkjvfnby — CHANGES_REQUESTED** [review]
Need to add one more test to a special value. 

What else can be checked in each test?

**Comment by LinaKrevetochka** [comment]
> Need to add one more test to a special value.
> 
> What else can be checked in each test?

I guess we can check that type of the parameter is string.

**Comment by Cjkjvfnby** [comment]
1) what special string should be tested?

2) what else can be checked in each test?

**Comment by LinaKrevetochka** [comment]
> 1. what special string should be tested?
> 2. what else can be checked in each test?

1. Are you talking about an empty string?
2.We can check another part of output.

**Review by Cjkjvfnby — APPROVED** [review]

**Pull request merged**
